### ISSUE TITLE
About ReverseEngineer method.

### ISSUE THREAD

**Issue by x9517536607** [GitYCC/tbrain_esun_house_price_predict#4]
Please tell me how did you get that?

**Comment by GitYCC** [comment]
1. 房價的真實數據應該呈去零頭的狀態，例如：1000萬、1100萬之類的，不大可能會是1120萬這種奇怪的數字
2. 我們把官方給的神秘轉換過後的數值攤開來看，的確發現有群聚的狀況，並且發現這些群聚兩兩相鄰價格差距會隨金額增加而遞增，代表神秘轉換不是線性的
3. 大概算了一下斜率變化得知跟 exponential curve 比較相近，實際去fit曲線又發現不是很準，但是指數項接近2/3
4. 從官方給的數據中觀察，發現值有一些竟然是整數，而且很多都是以 96452 結尾的，當下就猜 96452 應為加上去的常數 (其實是196452)
5. 然後扣除196452後，再用exponential轉換，其他的係數就很好猜了
6. 將逆轉換過後的結果放進去fit，發現有效果，多多少少增加了我們對這個reverse engineer的信心
