### ISSUE TITLE
關於最後的一部份的做法

### ISSUE THREAD

**Issue by damonchien** [GitYCC/tbrain_esun_house_price_predict#8]
這邊想請問作者的是
所以是對於每個預測的y都找到一個x使得P(x|y)最大
並且這個方法的假設是 training set 跟 testing set 的分佈是非常相似的
否則會失效
以上想法有相同嗎

**Comment by chenchc** [comment]
Hi damonchien,
確實必須假設 training set 跟 testing set 的分佈類似才能使用這個方法。
我們的目標是讓預測價格可以得到最大的 hit rate 得分機率，
也就是最大化 P(hit rate 得分 | 預測價格 y) ，
然而由於真實價格有去零頭的狀況，
需要我們去微調 model 輸出的預測 y 才能最大化 P(hit rate 得分 | 微調後的預測價格 y')，
所以才引入貝氏定理作為微調的策略。

**Comment by GitYCC** [comment]
貝氏定理的精髓就在可以基於過去資料分布去猜測和修正當下的一筆預測，而所有的ML問題都可以看成從母群體抽樣，再用這些資料去學習，所以training set和testing set應該要來自一樣的母群體，否則我們根本無從學習和預測。
